"""Estrutura inicial das tabelas principais

Revision ID: 065fbaf1821b
Revises: 
Create Date: 2026-06-13 17:15:32.031303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065fbaf1821b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_worker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('preco_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.create_table('contratacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('valor_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'SOLICITADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statuscontratacao'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratacoes_id'), 'contratacoes', ['id'], unique=False)
    op.create_table('avaliacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contratacao_id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.CheckConstraint('nota >= 1 AND nota <= 5', name='check_nota_range'),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratacao_id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_index(op.f('ix_contratacoes_id'), table_name='contratacoes')
    op.drop_table('contratacoes')
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###