"""create_auditoria_table

Revision ID: 469af94d7d08
Revises: b106861bb182
Create Date: 2026-06-15 14:46:35.068017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469af94d7d08'
down_revision: Union[str, None] = 'b106861bb182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_contratacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contratacao_id', sa.UUID(), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=True),
    sa.Column('status_novo', sa.String(length=50), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria_contratacoes')
    # ### end Alembic commands ###