"""add_motivo_cancelamento

Revision ID: b106861bb182
Revises: 065fbaf1821b
Create Date: 2026-06-15 14:41:18.449644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b106861bb182'
down_revision: Union[str, None] = '065fbaf1821b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratacoes', sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_contratacoes_id'), table_name='contratacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contratacoes_id'), 'contratacoes', ['id'], unique=False)
    op.drop_column('contratacoes', 'motivo_cancelamento')
    # ### end Alembic commands ###